FutureImperfect:
  about:
    siteName: 'Orchid Starter'
    tagline: 'Basic starter repo to get going with Orchid quickly'
    blurb: 'This is a short blurb you can set below this index layouts sidebar.'
    avatar: '/assets/images/logo.jpg'
  social:
    facebook: 'http://example.com/'
    twitter: 'http://example.com/'
    instagram: 'http://example.com/'
    rss: 'http://example.com/'
    email: 'http://example.com/'
  topMenu:
    - type: 'link'
      title: 'Home'
      url: '/'
    - type: 'postCategories'
      category: 'category1'
      title: 'blog'
    - type: 'page'
      page: 'Example Page'
  drawerMenu:
    - type: 'link'
      title: 'Home'
      url: '/'
    - type: 'postCategories'
      category: 'category1'
      title: 'blog'
    - type: 'page'
      page: 'Example Page'
  sidebar:
    - type: recentPosts
      limit: 3
      category: category1
      templates:
          - 'includes/postPreview_mini.twig'
    - type: recentPosts
      limit: 5
      category: category2
      templates:
          - 'includes/postPreview_list.twig'

assets:
  sourceDirs:
    - 'assets/images'

pages:
  layout: single

posts:
  layout: single
  permalink: ':category/:year/:month/:slug'
  disqusShortname: 'exampleShortname'
  categories:
    - 'category1'
    - 'category2'
  authors:
    - name: 'Author One'
      avatar: '/assets/images/avatar.jpg'

generators:
  disabled:
    - 'WikiGenerator'
    - 'IndexGenerator'
    - 'JavadocGenerator'
    - 'ChangelogGenerator'
    - 'KssGenerator'
