site:
  about:
    siteName: 'Orchid Starter'
    tagline: 'Basic starter repo to get going with Orchid quickly'
    blurb: 'This is a short blurb you can set below this index layouts sidebar.'
    avatar: '/assets/media/logo.jpg'

theme:
  social:
    facebook: 'facebookUsername'
    twitter: 'twitterHandle'
    instagram: 'instagramHandle'
    github: 'githubUsername'
  topMenu:
    - type: 'link'
      title: 'Home'
      url: '/'
    - type: 'postCategories'
      category: 'category1'
      title: 'blog'
    - type: 'page'
      page: 'Example Page'
  drawerMenu:
    - type: 'link'
      title: 'Home'
      url: '/'
    - type: 'postCategories'
      category: 'category1'
      title: 'blog'
    - type: 'page'
      page: 'Example Page'
  sidebar:
    - type: recentPosts
      limit: 3
      category: category1
      noWrapper: true
      templates:
          - 'includes/postPreview_mini'
    - type: recentPosts
      limit: 5
      category: category2
      noWrapper: true
      templates:
          - 'includes/postPreview_list'
  extraCss:
    - 'assets/css/extraCss.scss'
  extraJs:
    - 'assets/js/extraJs.js'

assets:
  sourceDirs:
    - 'assets'

posts:
  permalink: ':category/:year/:monthName/:slug'
  categories:
    - 'category1'
    - 'category2'
  authors:
    - name: 'Author One'
      avatar: '/assets/images/avatar.jpg'

generators:
  disabled:
    - 'WikiGenerator'
    - 'JavadocGenerator'
    - 'ChangelogGenerator'
    - 'KssGenerator'

staticPages:
  layout: single

postPages:
  layout: single

postArchivePages:
  layout: frontPage

netlifyCms:
  backend:
    name: github
    repo: 'Set Github repo as user/repo here'
    branch: master